name = "javascript_mutable_reference"
version = "1.0.0"
target = "javascript"
description = "Mutable references for Gleam JavaScript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "javascript-mutable-reference" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
